---
    - name: install python v2
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
    - name: Copy docker-compose file to remote server
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: run couchdb with docker    
      shell: |
       cd /home/ubuntu && docker-compose up -d
